package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Announcement generated by hbm2java
 */
public class Announcement  implements java.io.Serializable {


     private long announcementId;
     private User userByCreatedBy;
     private String name;
     private String description;
     private Date dateCreated;

    public Announcement() {
    }

	
    public Announcement(User userByCreatedBy, String name,  String description, Date dateCreated) {
    	this.userByCreatedBy = userByCreatedBy;
    	this.name = name;
    	this.description = description;
    	this.dateCreated = dateCreated;
    }

   
    public long getAnnouncementId() {
        return this.announcementId;
    }
    
    public void setAnnouncementId(long announcementId) {
        this.announcementId = announcementId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
 
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }



}


