package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * ApprovalRequest generated by hbm2java
 */
public class ApprovalRequest  implements java.io.Serializable {


     private long requestId;
     private User userByCreatedBy;
     private ApprovalRequestType approvalRequestType;
     private User userByUpdatedBy;
     private User userByRequestorId;
     private StatusValue statusValue;
     private User userByApproverId;
     private String comment;
     private Date dateCreated;
     private Date dateUpdated;
     private long parentKeyValue;

    public ApprovalRequest() {
    }

	
    public ApprovalRequest(User userByCreatedBy, ApprovalRequestType approvalRequestType, User userByRequestorId, StatusValue statusValue, Date dateCreated, long parentKeyValue) {
        this.userByCreatedBy = userByCreatedBy;
        this.approvalRequestType = approvalRequestType;
        this.userByRequestorId = userByRequestorId;
        this.statusValue = statusValue;
        this.dateCreated = dateCreated;
        this.parentKeyValue = parentKeyValue;
    }
    public ApprovalRequest(User userByCreatedBy, ApprovalRequestType approvalRequestType, User userByUpdatedBy, User userByRequestorId, StatusValue statusValue, User userByApproverId, String comment, Date dateCreated, Date dateUpdated) {

       this.userByCreatedBy = userByCreatedBy;
       this.approvalRequestType = approvalRequestType;
       this.userByUpdatedBy = userByUpdatedBy;
       this.userByRequestorId = userByRequestorId;
       this.statusValue = statusValue;
       this.userByApproverId = userByApproverId;
       this.comment = comment;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
    public long getRequestId() {
        return this.requestId;
    }
    
    public void setRequestId(long requestId) {
        this.requestId = requestId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public ApprovalRequestType getApprovalRequestType() {
        return this.approvalRequestType;
    }
    
    public void setApprovalRequestType(ApprovalRequestType approvalRequestType) {
        this.approvalRequestType = approvalRequestType;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public User getUserByRequestorId() {
        return this.userByRequestorId;
    }
    
    public void setUserByRequestorId(User userByRequestorId) {
        this.userByRequestorId = userByRequestorId;
    }
    public StatusValue getStatusValue() {
        return this.statusValue;
    }
    
    public void setStatusValue(StatusValue statusValue) {
        this.statusValue = statusValue;
    }
    public User getUserByApproverId() {
        return this.userByApproverId;
    }
    
    public void setUserByApproverId(User userByApproverId) {
        this.userByApproverId = userByApproverId;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public long getParentKeyValue() {
        return this.parentKeyValue;
    }
    
    public void setParentKeyValue(long parentKeyValue) {
        this.parentKeyValue = parentKeyValue;
    }



}


