package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * ApprovalRequestType generated by hbm2java
 */
public class ApprovalRequestType  implements java.io.Serializable {


     private long typeId;
     private String name;
     private String className;
     private String pkName;
     private Set approvalRequests = new HashSet(0);

    public ApprovalRequestType() {
    }

	
    public ApprovalRequestType(String name, String className, String pkName) {

        this.name = name;
        this.className = className;
        this.pkName = pkName;
    }
    public ApprovalRequestType(long typeId, String name, String className, String pkName, Set approvalRequests) {
       this.typeId = typeId;
       this.name = name;
       this.className = className;
       this.pkName = pkName;
       this.approvalRequests = approvalRequests;
    }
   
    public long getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(long typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public String getPkName() {
        return this.pkName;
    }
    
    public void setPkName(String pkName) {
        this.pkName = pkName;
    }
    public Set getApprovalRequests() {
        return this.approvalRequests;
    }
    
    public void setApprovalRequests(Set approvalRequests) {
        this.approvalRequests = approvalRequests;
    }




}


