package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dictionary generated by hbm2java
 */
public class Dictionary  implements java.io.Serializable {


     private long dictionaryId;
     private User userByCreatedBy;
     private User userByUpdatedBy;
     private StatusValue statusValue;
     private String name;
     private String description;
     private Date dateCreated;
     private Date dateUpdated;
     private String dictionaryCode;
     private Set dictionaryTerms = new HashSet(0);

    public Dictionary() {
    }

	
    public Dictionary(User userByCreatedBy, StatusValue statusValue, String name, String description, Date dateCreated, String dictionaryCode) {

        this.userByCreatedBy = userByCreatedBy;
        this.statusValue = statusValue;
        this.name = name;
        this.description = description;
        this.dateCreated = dateCreated;
        this.dictionaryCode = dictionaryCode;
    }
    public Dictionary(long dictionaryId, User userByCreatedBy, User userByUpdatedBy, StatusValue statusValue, String name, String description, Date dateCreated, Date dateUpdated, String dictionaryCode, Set dictionaryTerms) {
       this.dictionaryId = dictionaryId;
       this.userByCreatedBy = userByCreatedBy;
       this.userByUpdatedBy = userByUpdatedBy;
       this.statusValue = statusValue;
       this.name = name;
       this.description = description;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.dictionaryCode = dictionaryCode;
       this.dictionaryTerms = dictionaryTerms;
    }
   
    public long getDictionaryId() {
        return this.dictionaryId;
    }
    
    public void setDictionaryId(long dictionaryId) {
        this.dictionaryId = dictionaryId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public StatusValue getStatusValue() {
        return this.statusValue;
    }
    
    public void setStatusValue(StatusValue statusValue) {
        this.statusValue = statusValue;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public String getDictionaryCode() {
        return this.dictionaryCode;
    }
    
    public void setDictionaryCode(String dictionaryCode) {
        this.dictionaryCode = dictionaryCode;
    }
    public Set getDictionaryTerms() {
        return this.dictionaryTerms;
    }
    
    public void setDictionaryTerms(Set dictionaryTerms) {
        this.dictionaryTerms = dictionaryTerms;
    }




}


