package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DictionaryTerm generated by hbm2java
 */
public class DictionaryTerm  implements java.io.Serializable {


     private long termId;
     private User userByCreatedBy;
     private User userByUpdatedBy;
     private Dictionary dictionary;
     private StatusValue statusValue;
     private String term;
     private String description;
     private Date dateCreated;
     private Date dateUpdated;
     private Set observationTuplesForParamCatId = new HashSet(0);
     private Set observationTuplesForParamTypeId = new HashSet(0);
     private Set observationParametersForSamplingDepthId = new HashSet(0);
     private Set observationTuplesForAnalysisMethodId = new HashSet(0);
     private Set projectsForPurposeCategoryId = new HashSet(0);
     private Set projectsForAvailabilityId = new HashSet(0);
     private Set observationParametersForSamplingFreqId = new HashSet(0);
     private Set observationTuplesForMediumId = new HashSet(0);
     private Set projectsForProprietaryRestrictionId = new HashSet(0);

    public DictionaryTerm() {
    }

	
    public DictionaryTerm(User userByCreatedBy, Dictionary dictionary, StatusValue statusValue, String term, String description, Date dateCreated) {

        this.userByCreatedBy = userByCreatedBy;
        this.dictionary = dictionary;
        this.statusValue = statusValue;
        this.term = term;
        this.description = description;
        this.dateCreated = dateCreated;
    }
    public DictionaryTerm(long termId, User userByCreatedBy, User userByUpdatedBy, Dictionary dictionary, StatusValue statusValue, String term, String description, Date dateCreated, Date dateUpdated, Set observationTuplesForParamCatId, Set observationTuplesForParamTypeId, Set observationParametersForSamplingDepthId, Set observationTuplesForAnalysisMethodId, Set projectsForPurposeCategoryId, Set projectsForAvailabilityId, Set observationParametersForSamplingFreqId, Set observationTuplesForMediumId, Set projectsForProprietaryRestrictionId) {
       this.termId = termId;
       this.userByCreatedBy = userByCreatedBy;
       this.userByUpdatedBy = userByUpdatedBy;
       this.dictionary = dictionary;
       this.statusValue = statusValue;
       this.term = term;
       this.description = description;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.observationTuplesForParamCatId = observationTuplesForParamCatId;
       this.observationTuplesForParamTypeId = observationTuplesForParamTypeId;
       this.observationParametersForSamplingDepthId = observationParametersForSamplingDepthId;
       this.observationTuplesForAnalysisMethodId = observationTuplesForAnalysisMethodId;
       this.projectsForPurposeCategoryId = projectsForPurposeCategoryId;
       this.projectsForAvailabilityId = projectsForAvailabilityId;
       this.observationParametersForSamplingFreqId = observationParametersForSamplingFreqId;
       this.observationTuplesForMediumId = observationTuplesForMediumId;
       this.projectsForProprietaryRestrictionId = projectsForProprietaryRestrictionId;
    }
   
    public long getTermId() {
        return this.termId;
    }
    
    public void setTermId(long termId) {
        this.termId = termId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public Dictionary getDictionary() {
        return this.dictionary;
    }
    
    public void setDictionary(Dictionary dictionary) {
        this.dictionary = dictionary;
    }
    public StatusValue getStatusValue() {
        return this.statusValue;
    }
    
    public void setStatusValue(StatusValue statusValue) {
        this.statusValue = statusValue;
    }
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public Set getObservationTuplesForParamCatId() {
        return this.observationTuplesForParamCatId;
    }
    
    public void setObservationTuplesForParamCatId(Set observationTuplesForParamCatId) {
        this.observationTuplesForParamCatId = observationTuplesForParamCatId;
    }
    public Set getObservationTuplesForParamTypeId() {
        return this.observationTuplesForParamTypeId;
    }
    
    public void setObservationTuplesForParamTypeId(Set observationTuplesForParamTypeId) {
        this.observationTuplesForParamTypeId = observationTuplesForParamTypeId;
    }
    public Set getObservationParametersForSamplingDepthId() {
        return this.observationParametersForSamplingDepthId;
    }
    
    public void setObservationParametersForSamplingDepthId(Set observationParametersForSamplingDepthId) {
        this.observationParametersForSamplingDepthId = observationParametersForSamplingDepthId;
    }
    public Set getObservationTuplesForAnalysisMethodId() {
        return this.observationTuplesForAnalysisMethodId;
    }
    
    public void setObservationTuplesForAnalysisMethodId(Set observationTuplesForAnalysisMethodId) {
        this.observationTuplesForAnalysisMethodId = observationTuplesForAnalysisMethodId;
    }
    public Set getProjectsForPurposeCategoryId() {
        return this.projectsForPurposeCategoryId;
    }
    
    public void setProjectsForPurposeCategoryId(Set projectsForPurposeCategoryId) {
        this.projectsForPurposeCategoryId = projectsForPurposeCategoryId;
    }
    public Set getProjectsForAvailabilityId() {
        return this.projectsForAvailabilityId;
    }
    
    public void setProjectsForAvailabilityId(Set projectsForAvailabilityId) {
        this.projectsForAvailabilityId = projectsForAvailabilityId;
    }
    public Set getObservationParametersForSamplingFreqId() {
        return this.observationParametersForSamplingFreqId;
    }
    
    public void setObservationParametersForSamplingFreqId(Set observationParametersForSamplingFreqId) {
        this.observationParametersForSamplingFreqId = observationParametersForSamplingFreqId;
    }
    public Set getObservationTuplesForMediumId() {
        return this.observationTuplesForMediumId;
    }
    
    public void setObservationTuplesForMediumId(Set observationTuplesForMediumId) {
        this.observationTuplesForMediumId = observationTuplesForMediumId;
    }
    public Set getProjectsForProprietaryRestrictionId() {
        return this.projectsForProprietaryRestrictionId;
    }
    
    public void setProjectsForProprietaryRestrictionId(Set projectsForProprietaryRestrictionId) {
        this.projectsForProprietaryRestrictionId = projectsForProprietaryRestrictionId;
    }




}


