package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;
import java.util.Date;

/**
 * GeographicZone generated by hbm2java
 */
public class GeographicZone  implements java.io.Serializable {


     private long gzId;
     private User userByCreatedBy;
     private User userByUpdatedBy;
     private StatusValue statusValue;
     private String name;
     private String description;
     private String locationStr;
     private String keywords;
     private Date dateCreated;
     private Date dateUpdated;

    public GeographicZone() {
    }

	
    public GeographicZone(User userByCreatedBy, StatusValue statusValue, String name, String description, String locationStr,  Date dateCreated) {

        this.userByCreatedBy = userByCreatedBy;
        this.statusValue = statusValue;
        this.name = name;
        this.description = description;
        this.locationStr = locationStr;
        this.dateCreated = dateCreated;
    }
    public GeographicZone(long gzId, User userByCreatedBy, User userByUpdatedBy, StatusValue statusValue, String name, String description, String locationStr, String keywords, Date dateCreated, Date dateUpdated) {
       this.gzId = gzId;
       this.userByCreatedBy = userByCreatedBy;
       this.userByUpdatedBy = userByUpdatedBy;
       this.statusValue = statusValue;
       this.name = name;
       this.description = description;
       this.locationStr = locationStr;
       this.keywords = keywords;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
    public long getGzId() {
        return this.gzId;
    }
    
    public void setGzId(long gzId) {
        this.gzId = gzId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public StatusValue getStatusValue() {
        return this.statusValue;
    }
    
    public void setStatusValue(StatusValue statusValue) {
        this.statusValue = statusValue;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLocationStr() {
        return this.locationStr;
    }
    
    public void setLocationStr(String locationStr) {
        this.locationStr = locationStr;
    }
    
    public String getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


