package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * ObservationParameter generated by hbm2java
 */
public class ObservationParameter  implements java.io.Serializable {


     private long observationParamId;
     private User userByCreatedBy;
     private DictionaryTerm dictionaryTermBySamplingFreqId;
     private ObservationTuple observationTuple;
     private Station station;
     private User userByUpdatedBy;
     private StatusValue statusValue;
     private DictionaryTerm dictionaryTermBySamplingDepthId;
     private Date startDate;
     private Date endDate;
     private Date dateCreated;
     private Date dateUpdated;

    public ObservationParameter() {
    }

	
    public ObservationParameter(User userByCreatedBy, DictionaryTerm dictionaryTermBySamplingFreqId, ObservationTuple observationTuple, Station station, StatusValue statusValue, Date dateCreated) {

        this.userByCreatedBy = userByCreatedBy;
        this.dictionaryTermBySamplingFreqId = dictionaryTermBySamplingFreqId;
        this.observationTuple = observationTuple;
        this.station = station;
        this.statusValue = statusValue;
        this.dateCreated = dateCreated;
    }
    public ObservationParameter(long observationParamId, User userByCreatedBy, DictionaryTerm dictionaryTermBySamplingFreqId, ObservationTuple observationTuple, Station station, User userByUpdatedBy, StatusValue statusValue, DictionaryTerm dictionaryTermBySamplingDepthId, Date startDate, Date endDate, Date dateCreated, Date dateUpdated) {
       this.observationParamId = observationParamId;
       this.userByCreatedBy = userByCreatedBy;
       this.dictionaryTermBySamplingFreqId = dictionaryTermBySamplingFreqId;
       this.observationTuple = observationTuple;
       this.station = station;
       this.userByUpdatedBy = userByUpdatedBy;
       this.statusValue = statusValue;
       this.dictionaryTermBySamplingDepthId = dictionaryTermBySamplingDepthId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
    }
   
    public long getObservationParamId() {
        return this.observationParamId;
    }
    
    public void setObservationParamId(long observationParamId) {
        this.observationParamId = observationParamId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public DictionaryTerm getDictionaryTermBySamplingFreqId() {
        return this.dictionaryTermBySamplingFreqId;
    }
    
    public void setDictionaryTermBySamplingFreqId(DictionaryTerm dictionaryTermBySamplingFreqId) {
        this.dictionaryTermBySamplingFreqId = dictionaryTermBySamplingFreqId;
    }
    public ObservationTuple getObservationTuple() {
        return this.observationTuple;
    }
    
    public void setObservationTuple(ObservationTuple observationTuple) {
        this.observationTuple = observationTuple;
    }
    public Station getStation() {
        return this.station;
    }
    
    public void setStation(Station station) {
        this.station = station;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public StatusValue getStatusValue() {
        return this.statusValue;
    }
    
    public void setStatusValue(StatusValue statusValue) {
        this.statusValue = statusValue;
    }
    public DictionaryTerm getDictionaryTermBySamplingDepthId() {
        return this.dictionaryTermBySamplingDepthId;
    }
    
    public void setDictionaryTermBySamplingDepthId(DictionaryTerm dictionaryTermBySamplingDepthId) {
        this.dictionaryTermBySamplingDepthId = dictionaryTermBySamplingDepthId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


