package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ObservationTuple generated by hbm2java
 */
public class ObservationTuple  implements java.io.Serializable {


     private long observationTupleId;
     private User userByCreatedBy;
     private DictionaryTerm dictionaryTermByMediumId;
     private DictionaryTerm dictionaryTermByParamTypeId;
     private DictionaryTerm dictionaryTermByParamCatId;
     private User userByUpdatedBy;
     private StatusValue statusValue;
     private DictionaryTerm dictionaryTermByAnalysisMethodId;
     private Date dateCreated;
     private Date dateUpdated;
     private Set observationParameters = new HashSet(0);

    public ObservationTuple() {
    }

	
    public ObservationTuple(User userByCreatedBy, DictionaryTerm dictionaryTermByMediumId, DictionaryTerm dictionaryTermByParamTypeId, DictionaryTerm dictionaryTermByParamCatId, StatusValue statusValue, DictionaryTerm dictionaryTermByAnalysisMethodId, Date dateCreated) {

        this.userByCreatedBy = userByCreatedBy;
        this.dictionaryTermByMediumId = dictionaryTermByMediumId;
        this.dictionaryTermByParamTypeId = dictionaryTermByParamTypeId;
        this.dictionaryTermByParamCatId = dictionaryTermByParamCatId;
        this.statusValue = statusValue;
        this.dictionaryTermByAnalysisMethodId = dictionaryTermByAnalysisMethodId;
        this.dateCreated = dateCreated;
    }
    public ObservationTuple(long observationTupleId, User userByCreatedBy, DictionaryTerm dictionaryTermByMediumId, DictionaryTerm dictionaryTermByParamTypeId, DictionaryTerm dictionaryTermByParamCatId, User userByUpdatedBy, StatusValue statusValue, DictionaryTerm dictionaryTermByAnalysisMethodId, Date dateCreated, Date dateUpdated, Set observationParameters) {
       this.observationTupleId = observationTupleId;
       this.userByCreatedBy = userByCreatedBy;
       this.dictionaryTermByMediumId = dictionaryTermByMediumId;
       this.dictionaryTermByParamTypeId = dictionaryTermByParamTypeId;
       this.dictionaryTermByParamCatId = dictionaryTermByParamCatId;
       this.userByUpdatedBy = userByUpdatedBy;
       this.statusValue = statusValue;
       this.dictionaryTermByAnalysisMethodId = dictionaryTermByAnalysisMethodId;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.observationParameters = observationParameters;
    }
   
    public long getObservationTupleId() {
        return this.observationTupleId;
    }
    
    public void setObservationTupleId(long observationTupleId) {
        this.observationTupleId = observationTupleId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public DictionaryTerm getDictionaryTermByMediumId() {
        return this.dictionaryTermByMediumId;
    }
    
    public void setDictionaryTermByMediumId(DictionaryTerm dictionaryTermByMediumId) {
        this.dictionaryTermByMediumId = dictionaryTermByMediumId;
    }
    public DictionaryTerm getDictionaryTermByParamTypeId() {
        return this.dictionaryTermByParamTypeId;
    }
    
    public void setDictionaryTermByParamTypeId(DictionaryTerm dictionaryTermByParamTypeId) {
        this.dictionaryTermByParamTypeId = dictionaryTermByParamTypeId;
    }
    public DictionaryTerm getDictionaryTermByParamCatId() {
        return this.dictionaryTermByParamCatId;
    }
    
    public void setDictionaryTermByParamCatId(DictionaryTerm dictionaryTermByParamCatId) {
        this.dictionaryTermByParamCatId = dictionaryTermByParamCatId;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public StatusValue getStatusValue() {
        return this.statusValue;
    }
    
    public void setStatusValue(StatusValue statusValue) {
        this.statusValue = statusValue;
    }
    public DictionaryTerm getDictionaryTermByAnalysisMethodId() {
        return this.dictionaryTermByAnalysisMethodId;
    }
    
    public void setDictionaryTermByAnalysisMethodId(DictionaryTerm dictionaryTermByAnalysisMethodId) {
        this.dictionaryTermByAnalysisMethodId = dictionaryTermByAnalysisMethodId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public Set getObservationParameters() {
        return this.observationParameters;
    }
    
    public void setObservationParameters(Set observationParameters) {
        this.observationParameters = observationParameters;
    }




}


