package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * OrganizationType generated by hbm2java
 */
public class OrganizationType  implements java.io.Serializable {


     private long typeId;
     private String type;
     private Set organizations = new HashSet(0);

    public OrganizationType() {
    }

	
    public OrganizationType(String type) {

        this.type = type;
    }
    public OrganizationType(long typeId, String type, Set organizations) {
       this.typeId = typeId;
       this.type = type;
       this.organizations = organizations;
    }
   
    public long getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(long typeId) {
        this.typeId = typeId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getOrganizations() {
        return this.organizations;
    }
    
    public void setOrganizations(Set organizations) {
        this.organizations = organizations;
    }




}


