package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization  implements java.io.Serializable {


     private long organizationId;
     private User userByCreatedBy;
     private OrganizationType organizationType;
     private User userByUpdatedBy;
     private String name;
     private String description;
     private String website;
     private Date dateCreated;
     private Date dateUpdated;
     private Set users = new HashSet(0);
     private Set stations = new HashSet(0);
     private Set programs = new HashSet(0);

    public Organization() {
    }

	
    public Organization(User userByCreatedBy, OrganizationType organizationType, String name, String description, Date dateCreated) {

        this.userByCreatedBy = userByCreatedBy;
        this.organizationType = organizationType;
        this.name = name;
        this.description = description;
        this.dateCreated = dateCreated;
    }
    public Organization(long organizationId, User userByCreatedBy, OrganizationType organizationType, User userByUpdatedBy, String name, String description, String website, Date dateCreated, Date dateUpdated, Set users, Set stations, Set programs) {
       this.organizationId = organizationId;
       this.userByCreatedBy = userByCreatedBy;
       this.organizationType = organizationType;
       this.userByUpdatedBy = userByUpdatedBy;
       this.name = name;
       this.description = description;
       this.website = website;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.users = users;
       this.stations = stations;
       this.programs = programs;
    }
   
    public long getOrganizationId() {
        return this.organizationId;
    }
    
    public void setOrganizationId(long organizationId) {
        this.organizationId = organizationId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public OrganizationType getOrganizationType() {
        return this.organizationType;
    }
    
    public void setOrganizationType(OrganizationType organizationType) {
        this.organizationType = organizationType;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getStations() {
        return this.stations;
    }
    
    public void setStations(Set stations) {
        this.stations = stations;
    }
    public Set getPrograms() {
        return this.programs;
    }
    
    public void setPrograms(Set programs) {
        this.programs = programs;
    }




}


