package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1



/**
 * ProgramAdminId generated by hbm2java
 */
public class ProgramAdminId  implements java.io.Serializable {


     private Long userId;
     private Long programId;

    public ProgramAdminId() {
    }

    public ProgramAdminId(Long userId, Long programId) {
       this.userId = userId;
       this.programId = programId;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public Long getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(Long programId) {
        this.programId = programId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProgramAdminId) ) return false;
		 ProgramAdminId castOther = ( ProgramAdminId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getProgramId()==castOther.getProgramId()) || ( this.getProgramId()!=null && castOther.getProgramId()!=null && this.getProgramId().equals(castOther.getProgramId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getProgramId() == null ? 0 : this.getProgramId().hashCode() );
         return result;
   }   


}


