package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1



/**
 * ProgramAdmin generated by hbm2java
 */
public class ProgramAdmin  implements java.io.Serializable {


     private ProgramAdminId id;
     private User user;
     private Program program;

    public ProgramAdmin() {
    }

	
    public ProgramAdmin(ProgramAdminId id) {
        this.id = id;
    }
    public ProgramAdmin(ProgramAdminId id, User user, Program program) {
       this.id = id;
       this.user = user;
       this.program = program;
    }
   
    public ProgramAdminId getId() {
        return this.id;
    }
    
    public void setId(ProgramAdminId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }




}


