package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * ProgramManager generated by hbm2java
 */
public class ProgramManager  implements java.io.Serializable {


     private long programManagerId;
     private Person person;
     private Set programs = new HashSet(0);

    public ProgramManager() {
    }

	
    public ProgramManager(Person person) {

        this.person = person;
    }
    public ProgramManager(Person person, Set programs) {

       this.person = person;
       this.programs = programs;
    }
   
    public long getProgramManagerId() {
        return this.programManagerId;
    }
    
    public void setProgramManagerId(long programManagerId) {
        this.programManagerId = programManagerId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Set getPrograms() {
        return this.programs;
    }
    
    public void setPrograms(Set programs) {
        this.programs = programs;
    }




}


