package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * ProjectManager generated by hbm2java
 */
public class ProjectManager  implements java.io.Serializable {


     private long projectManagerId;
     private Person person;
     private Set projects = new HashSet(0);

    public ProjectManager() {
    }

	
    public ProjectManager(Person person) {

        this.person = person;
    }
    public ProjectManager(long projectManagerId, Person person, Set projects) {
       this.projectManagerId = projectManagerId;
       this.person = person;
       this.projects = projects;
    }
   
    public long getProjectManagerId() {
        return this.projectManagerId;
    }
    
    public void setProjectManagerId(long projectManagerId) {
        this.projectManagerId = projectManagerId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }




}


