package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private long projectId;
     private User userByCreatedBy;
     private DictionaryTerm dictionaryTermByProprietaryRestrictionId;
     private DataDistributor dataDistributor;
     private Program program;
     private ProjectManager projectManager;
     private User userByUpdatedBy;
     private DictionaryTerm dictionaryTermByPurposeCategoryId;
     private StatusValue statusValueByApprovalStatusId;
     private DictionaryTerm dictionaryTermByAvailabilityId;
     private DictionaryTerm dictionaryTermByProjectMethodologyId;
     private StatusValue statusValueByStatusId;
     private String name;
     private String description;
     private String website;
     private String dataLinkWebsite;
     private String fax;
     private String usageLimitations;
     private String purposeText;
     private String dataQualityObj;
     private String geoBoundary;
     private Date startDate;
     private Date endDate;
     private Date dateCreated;
     private Date dateUpdated;
     private String proprietaryRestrictionText;
     private Set stations = new HashSet(0);
     private Set stationProjects = new HashSet(0);

    public Project() {
    }

	
    public Project(User userByCreatedBy, DictionaryTerm dictionaryTermByProprietaryRestrictionId, DataDistributor dataDistributor, Program program, ProjectManager projectManager, DictionaryTerm dictionaryTermByPurposeCategoryId, StatusValue statusValueByApprovalStatusId, DictionaryTerm dictionaryTermByAvailabilityId, StatusValue statusValueByStatusId, String name, String description, String purposeText, String dataQualityObj, Date startDate, Date endDate, Date dateCreated, DictionaryTerm dictionaryTermByProjectMethodologyId) {

        this.userByCreatedBy = userByCreatedBy;
        this.dictionaryTermByProprietaryRestrictionId = dictionaryTermByProprietaryRestrictionId;
        this.dataDistributor = dataDistributor;
        this.program = program;
        this.projectManager = projectManager;
        this.dictionaryTermByPurposeCategoryId = dictionaryTermByPurposeCategoryId;
        this.statusValueByApprovalStatusId = statusValueByApprovalStatusId;
        this.dictionaryTermByAvailabilityId = dictionaryTermByAvailabilityId;
        this.dictionaryTermByProjectMethodologyId = dictionaryTermByProjectMethodologyId;
        this.statusValueByStatusId = statusValueByStatusId;
        this.name = name;
        this.description = description;
        this.purposeText = purposeText;
        this.dataQualityObj = dataQualityObj;
        this.startDate = startDate;
        this.endDate = endDate;
        this.dateCreated = dateCreated;
    }
    public Project(long projectId, User userByCreatedBy, DictionaryTerm dictionaryTermByProprietaryRestrictionId, DataDistributor dataDistributor, Program program, ProjectManager projectManager, User userByUpdatedBy, DictionaryTerm dictionaryTermByPurposeCategoryId, StatusValue statusValueByApprovalStatusId, DictionaryTerm dictionaryTermByAvailabilityId, StatusValue statusValueByStatusId, String name, String description, String website, String dataLinkWebsite, String fax, String usageLimitations, String purposeText, String dataQualityObj, String geoBoundary, Date startDate, Date endDate, Date dateCreated, Date dateUpdated, String proprietaryRestrictionText, Set stations, Set stationProjects) {
       this.projectId = projectId;
       this.userByCreatedBy = userByCreatedBy;
       this.dictionaryTermByProprietaryRestrictionId = dictionaryTermByProprietaryRestrictionId;
       this.dataDistributor = dataDistributor;
       this.program = program;
       this.projectManager = projectManager;
       this.userByUpdatedBy = userByUpdatedBy;
       this.dictionaryTermByPurposeCategoryId = dictionaryTermByPurposeCategoryId;
       this.statusValueByApprovalStatusId = statusValueByApprovalStatusId;
       this.dictionaryTermByAvailabilityId = dictionaryTermByAvailabilityId;
       this.statusValueByStatusId = statusValueByStatusId;
       this.name = name;
       this.description = description;
       this.website = website;
       this.dataLinkWebsite = dataLinkWebsite;
       this.fax = fax;
       this.usageLimitations = usageLimitations;
       this.purposeText = purposeText;
       this.dataQualityObj = dataQualityObj;
       this.geoBoundary = geoBoundary;
       this.startDate = startDate;
       this.endDate = endDate;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.proprietaryRestrictionText = proprietaryRestrictionText;
       this.stations = stations;
       this.stationProjects = stationProjects;
    }
   
    public long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public DictionaryTerm getDictionaryTermByProprietaryRestrictionId() {
        return this.dictionaryTermByProprietaryRestrictionId;
    }
    
    public void setDictionaryTermByProprietaryRestrictionId(DictionaryTerm dictionaryTermByProprietaryRestrictionId) {
        this.dictionaryTermByProprietaryRestrictionId = dictionaryTermByProprietaryRestrictionId;
    }
    public DataDistributor getDataDistributor() {
        return this.dataDistributor;
    }
    
    public void setDataDistributor(DataDistributor dataDistributor) {
        this.dataDistributor = dataDistributor;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public ProjectManager getProjectManager() {
        return this.projectManager;
    }
    
    public void setProjectManager(ProjectManager projectManager) {
        this.projectManager = projectManager;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public DictionaryTerm getDictionaryTermByPurposeCategoryId() {
        return this.dictionaryTermByPurposeCategoryId;
    }
    
    public void setDictionaryTermByPurposeCategoryId(DictionaryTerm dictionaryTermByPurposeCategoryId) {
        this.dictionaryTermByPurposeCategoryId = dictionaryTermByPurposeCategoryId;
    }
    public StatusValue getStatusValueByApprovalStatusId() {
        return this.statusValueByApprovalStatusId;
    }
    
    public void setStatusValueByApprovalStatusId(StatusValue statusValueByApprovalStatusId) {
        this.statusValueByApprovalStatusId = statusValueByApprovalStatusId;
    }
    public DictionaryTerm getDictionaryTermByAvailabilityId() {
        return this.dictionaryTermByAvailabilityId;
    }
    
    public void setDictionaryTermByAvailabilityId(DictionaryTerm dictionaryTermByAvailabilityId) {
        this.dictionaryTermByAvailabilityId = dictionaryTermByAvailabilityId;
    }
    public StatusValue getStatusValueByStatusId() {
        return this.statusValueByStatusId;
    }
    
    public void setStatusValueByStatusId(StatusValue statusValueByStatusId) {
        this.statusValueByStatusId = statusValueByStatusId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getDataLinkWebsite() {
        return this.dataLinkWebsite;
    }
    
    public void setDataLinkWebsite(String dataLinkWebsite) {
        this.dataLinkWebsite = dataLinkWebsite;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getUsageLimitations() {
        return this.usageLimitations;
    }
    
    public void setUsageLimitations(String usageLimitations) {
        this.usageLimitations = usageLimitations;
    }
    public String getPurposeText() {
        return this.purposeText;
    }
    
    public void setPurposeText(String purposeText) {
        this.purposeText = purposeText;
    }
    public String getDataQualityObj() {
        return this.dataQualityObj;
    }
    
    public void setDataQualityObj(String dataQualityObj) {
        this.dataQualityObj = dataQualityObj;
    }
    public String getGeoBoundary() {
        return this.geoBoundary;
    }
    
    public void setGeoBoundary(String geoBoundary) {
        this.geoBoundary = geoBoundary;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public String getProprietaryRestrictionText() {
        return this.proprietaryRestrictionText;
    }
    
    public void setProprietaryRestrictionText(String proprietaryRestrictionText) {
        this.proprietaryRestrictionText = proprietaryRestrictionText;
    }
    public Set getStations() {
        return this.stations;
    }
    
    public void setStations(Set stations) {
        this.stations = stations;
    }
    public Set getStationProjects() {
        return this.stationProjects;
    }
    
    public void setStationProjects(Set stationProjects) {
        this.stationProjects = stationProjects;
    }


	public DictionaryTerm getDictionaryTermByProjectMethodologyId() {
		return dictionaryTermByProjectMethodologyId;
	}


	public void setDictionaryTermByProjectMethodologyId(
			DictionaryTerm dictionaryTermByProjectMethodologyId) {
		this.dictionaryTermByProjectMethodologyId = dictionaryTermByProjectMethodologyId;
	}




}


