package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernatespatial.GeometryUserType;

import com.vividsolutions.jts.geom.Geometry;

/**
 * Station generated by hbm2java
 */
public class Station  implements java.io.Serializable {


     private long stationId;
     private User userByCreatedBy;
     private Project project;
     private Program program;
     private Organization organization;
     private User userByUpdatedBy;
     private StatusValue statusValueByApprovalStatusId;
     private StatusValue statusValueByStatusId;
     private String name;
     private String description;
     private String website;
     private String keywords;
     private Date startDate;
     private Date endDate;
     private Date dateCreated;
     private Date dateUpdated;
     //private Serializable location;
     private String locationStr;
     private Set observationParameters = new HashSet(0);
     private Set stationProjects = new HashSet(0);

    public Station() {
    }

	
    public Station(User userByCreatedBy, Project project, Program program, Organization organization, StatusValue statusValueByApprovalStatusId, StatusValue statusValueByStatusId, String name, String description, Date dateCreated, String locationStr) {

        this.userByCreatedBy = userByCreatedBy;
        this.project = project;
        this.program = program;
        this.organization = organization;
        this.statusValueByApprovalStatusId = statusValueByApprovalStatusId;
        this.statusValueByStatusId = statusValueByStatusId;
        this.name = name;
        this.description = description;
        this.dateCreated = dateCreated;
        this.locationStr = locationStr;
    }
    public Station(User userByCreatedBy, Project project, Program program, Organization organization, StatusValue statusValueByApprovalStatusId, StatusValue statusValueByStatusId, String name, String description, Date dateCreated, String locationStr, String website, Date startDate, Date endDate) {

        this.userByCreatedBy = userByCreatedBy;
        this.project = project;
        this.program = program;
        this.organization = organization;
        this.statusValueByApprovalStatusId = statusValueByApprovalStatusId;
        this.statusValueByStatusId = statusValueByStatusId;
        this.name = name;
        this.description = description;
        this.dateCreated = dateCreated;
        this.locationStr = locationStr;
        this.website = website;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public Station(long stationId, User userByCreatedBy, Project project, Program program, Organization organization, User userByUpdatedBy, StatusValue statusValueByApprovalStatusId, StatusValue statusValueByStatusId, String name, String description, String website, String keywords, Date startDate, Date endDate, Date dateCreated, Date dateUpdated, String locationStr, Set observationParameters, Set stationProjects) {
       this.stationId = stationId;
       this.userByCreatedBy = userByCreatedBy;
       this.project = project;
       this.program = program;
       this.organization = organization;
       this.userByUpdatedBy = userByUpdatedBy;
       this.statusValueByApprovalStatusId = statusValueByApprovalStatusId;
       this.statusValueByStatusId = statusValueByStatusId;
       this.name = name;
       this.description = description;
       this.website = website;
       this.keywords = keywords;
       this.startDate = startDate;
       this.endDate = endDate;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
      // this.location = location;
       this.locationStr = locationStr;
       this.observationParameters = observationParameters;
       this.stationProjects = stationProjects;
    }
   
    public long getStationId() {
        return this.stationId;
    }
    
    public void setStationId(long stationId) {
        this.stationId = stationId;
    }
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public User getUserByUpdatedBy() {
        return this.userByUpdatedBy;
    }
    
    public void setUserByUpdatedBy(User userByUpdatedBy) {
        this.userByUpdatedBy = userByUpdatedBy;
    }
    public StatusValue getStatusValueByApprovalStatusId() {
        return this.statusValueByApprovalStatusId;
    }
    
    public void setStatusValueByApprovalStatusId(StatusValue statusValueByApprovalStatusId) {
        this.statusValueByApprovalStatusId = statusValueByApprovalStatusId;
    }
    public StatusValue getStatusValueByStatusId() {
        return this.statusValueByStatusId;
    }
    
    public void setStatusValueByStatusId(StatusValue statusValueByStatusId) {
        this.statusValueByStatusId = statusValueByStatusId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    /*
    public Serializable getLocation() {
        return this.location;
    }
    
    public void setLocation(Serializable location) {
        this.location = location;
    }
    */
    public String getLocationStr() {
        return this.locationStr;
    }
    
    public void setLocationStr(String locationStr) {
        this.locationStr = locationStr;
    }
    public Set getObservationParameters() {
        return this.observationParameters;
    }
    
    public void setObservationParameters(Set observationParameters) {
        this.observationParameters = observationParameters;
    }
    public Set getStationProjects() {
        return this.stationProjects;
    }
    
    public void setStationProjects(Set stationProjects) {
        this.stationProjects = stationProjects;
    }




}


