package edu.miami.ccs.goma.pojos;
// Generated Feb 20, 2012 3:22:28 PM by Hibernate Tools 3.4.0.CR1



/**
 * StationObservationParamId generated by hbm2java
 */
public class StationObservationParamId  implements java.io.Serializable {


     private StationObservationParamIdId id;
     private ObservationParameter observationParameter;
     private Station station;

    public StationObservationParamId() {
    }

    public StationObservationParamId(StationObservationParamIdId id, ObservationParameter observationParameter, Station station) {
       this.id = id;
       this.observationParameter = observationParameter;
       this.station = station;
    }
   
    public StationObservationParamIdId getId() {
        return this.id;
    }
    
    public void setId(StationObservationParamIdId id) {
        this.id = id;
    }
    public ObservationParameter getObservationParameter() {
        return this.observationParameter;
    }
    
    public void setObservationParameter(ObservationParameter observationParameter) {
        this.observationParameter = observationParameter;
    }
    public Station getStation() {
        return this.station;
    }
    
    public void setStation(Station station) {
        this.station = station;
    }




}


