package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * StatusValue generated by hbm2java
 */
public class StatusValue  implements java.io.Serializable {


     private long statusId;
     private StatusType statusType;
     private String statusCode;
     private String statusValue;
     private Set approvalRequests = new HashSet(0);
     private Set projectsForStatusId = new HashSet(0);
     private Set dictionaries = new HashSet(0);
     private Set observationTuples = new HashSet(0);
     private Set stationsForApprovalStatusId = new HashSet(0);
     private Set programsForApprovalStatusId = new HashSet(0);
     private Set programsForStatusId = new HashSet(0);
     private Set geographicZones = new HashSet(0);
     private Set projectsForApprovalStatusId = new HashSet(0);
     private Set stationsForStatusId = new HashSet(0);
     private Set dictionaryTerms = new HashSet(0);
     private Set observationParameters = new HashSet(0);

    public StatusValue() {
    }

	
    public StatusValue(StatusType statusType, String statusCode, String statusValue) {

        this.statusType = statusType;
        this.statusCode = statusCode;
        this.statusValue = statusValue;
    }
    public StatusValue(long statusId, StatusType statusType, String statusCode, String statusValue, Set approvalRequests, Set projectsForStatusId, Set dictionaries, Set observationTuples, Set stationsForApprovalStatusId, Set programsForApprovalStatusId, Set programsForStatusId, Set geographicZones, Set projectsForApprovalStatusId, Set stationsForStatusId, Set dictionaryTerms, Set observationParameters) {
       this.statusId = statusId;
       this.statusType = statusType;
       this.statusCode = statusCode;
       this.statusValue = statusValue;
       this.approvalRequests = approvalRequests;
       this.projectsForStatusId = projectsForStatusId;
       this.dictionaries = dictionaries;
       this.observationTuples = observationTuples;
       this.stationsForApprovalStatusId = stationsForApprovalStatusId;
       this.programsForApprovalStatusId = programsForApprovalStatusId;
       this.programsForStatusId = programsForStatusId;
       this.geographicZones = geographicZones;
       this.projectsForApprovalStatusId = projectsForApprovalStatusId;
       this.stationsForStatusId = stationsForStatusId;
       this.dictionaryTerms = dictionaryTerms;
       this.observationParameters = observationParameters;
    }
   
    public long getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(long statusId) {
        this.statusId = statusId;
    }
    public StatusType getStatusType() {
        return this.statusType;
    }
    
    public void setStatusType(StatusType statusType) {
        this.statusType = statusType;
    }
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }
    public String getStatusValue() {
        return this.statusValue;
    }
    
    public void setStatusValue(String statusValue) {
        this.statusValue = statusValue;
    }
    public Set getApprovalRequests() {
        return this.approvalRequests;
    }
    
    public void setApprovalRequests(Set approvalRequests) {
        this.approvalRequests = approvalRequests;
    }
    public Set getProjectsForStatusId() {
        return this.projectsForStatusId;
    }
    
    public void setProjectsForStatusId(Set projectsForStatusId) {
        this.projectsForStatusId = projectsForStatusId;
    }
    public Set getDictionaries() {
        return this.dictionaries;
    }
    
    public void setDictionaries(Set dictionaries) {
        this.dictionaries = dictionaries;
    }
    public Set getObservationTuples() {
        return this.observationTuples;
    }
    
    public void setObservationTuples(Set observationTuples) {
        this.observationTuples = observationTuples;
    }
    public Set getStationsForApprovalStatusId() {
        return this.stationsForApprovalStatusId;
    }
    
    public void setStationsForApprovalStatusId(Set stationsForApprovalStatusId) {
        this.stationsForApprovalStatusId = stationsForApprovalStatusId;
    }
    public Set getProgramsForApprovalStatusId() {
        return this.programsForApprovalStatusId;
    }
    
    public void setProgramsForApprovalStatusId(Set programsForApprovalStatusId) {
        this.programsForApprovalStatusId = programsForApprovalStatusId;
    }
    public Set getProgramsForStatusId() {
        return this.programsForStatusId;
    }
    
    public void setProgramsForStatusId(Set programsForStatusId) {
        this.programsForStatusId = programsForStatusId;
    }
    public Set getGeographicZones() {
        return this.geographicZones;
    }
    
    public void setGeographicZones(Set geographicZones) {
        this.geographicZones = geographicZones;
    }
    public Set getProjectsForApprovalStatusId() {
        return this.projectsForApprovalStatusId;
    }
    
    public void setProjectsForApprovalStatusId(Set projectsForApprovalStatusId) {
        this.projectsForApprovalStatusId = projectsForApprovalStatusId;
    }
    public Set getStationsForStatusId() {
        return this.stationsForStatusId;
    }
    
    public void setStationsForStatusId(Set stationsForStatusId) {
        this.stationsForStatusId = stationsForStatusId;
    }
    public Set getDictionaryTerms() {
        return this.dictionaryTerms;
    }
    
    public void setDictionaryTerms(Set dictionaryTerms) {
        this.dictionaryTerms = dictionaryTerms;
    }
    public Set getObservationParameters() {
        return this.observationParameters;
    }
    
    public void setObservationParameters(Set observationParameters) {
        this.observationParameters = observationParameters;
    }




}


