package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1



/**
 * StationProject generated by hbm2java
 */
public class StationProject  implements java.io.Serializable {


     private StationProjectId id;
     private Station station;
     private Project project;

    public StationProject() {
    }

    public StationProject(StationProjectId id, Station station, Project project) {
       this.id = id;
       this.station = station;
       this.project = project;
    }
   
    public StationProjectId getId() {
        return this.id;
    }
    
    public void setId(StationProjectId id) {
        this.id = id;
    }
    public Station getStation() {
        return this.station;
    }
    
    public void setStation(Station station) {
        this.station = station;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }




}


