package edu.miami.ccs.goma.pojos;
// Generated Feb 20, 2012 3:22:28 PM by Hibernate Tools 3.4.0.CR1



/**
 * StationObservationParamIdId generated by hbm2java
 */
public class StationObservationParamIdId  implements java.io.Serializable {


     private long stationId;
     private long observationParamId;

    public StationObservationParamIdId() {
    }

    public StationObservationParamIdId(long stationId, long observationParamId) {
       this.stationId = stationId;
       this.observationParamId = observationParamId;
    }
   
    public long getStationId() {
        return this.stationId;
    }
    
    public void setStationId(long stationId) {
        this.stationId = stationId;
    }
    public long getObservationParamId() {
        return this.observationParamId;
    }
    
    public void setObservationParamId(long observationParamId) {
        this.observationParamId = observationParamId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StationObservationParamIdId) ) return false;
		 StationObservationParamIdId castOther = ( StationObservationParamIdId ) other; 
         
		 return (this.getStationId()==castOther.getStationId())
 && (this.getObservationParamId()==castOther.getObservationParamId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getStationId();
         result = 37 * result + (int) this.getObservationParamId();
         return result;
   }   


}


