package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1



/**
 * StationProjectId generated by hbm2java
 */
public class StationProjectId  implements java.io.Serializable {


     private long projectId;
     private long stationId;

    public StationProjectId() {
    }

    public StationProjectId(long projectId, long stationId) {
       this.projectId = projectId;
       this.stationId = stationId;
    }
   
    public long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }
    public long getStationId() {
        return this.stationId;
    }
    
    public void setStationId(long stationId) {
        this.stationId = stationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StationProjectId) ) return false;
		 StationProjectId castOther = ( StationProjectId ) other; 
         
		 return (this.getProjectId()==castOther.getProjectId())
 && (this.getStationId()==castOther.getStationId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getProjectId();
         result = 37 * result + (int) this.getStationId();
         return result;
   }   


}


