package edu.miami.ccs.goma.pojos;
// Generated May 4, 2012 4:38:51 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private long userId;
     private Organization organization;
     private UserRole userRole;
     private Person person;
     private String username;
     private String password;
     private Date dateCreated;
     private Date dateUpdated;
     private Long updatedBy;
     private long createdBy;
     private Set approvalRequestsForUpdatedBy = new HashSet(0);
     private Set stationsForUpdatedBy = new HashSet(0);
     private Set dictionariesForUpdatedBy = new HashSet(0);
     private Set dictionaryTermsForUpdatedBy = new HashSet(0);
     private Set stationsForCreatedBy = new HashSet(0);
     private Set geographicZonesForUpdatedBy = new HashSet(0);
     private Set approvalRequestsForApproverId = new HashSet(0);
     private Set approvalRequestsForCreatedBy = new HashSet(0);
     private Set programsForUpdatedBy = new HashSet(0);
     private Set programAdmins = new HashSet(0);
     private Set programsForOwnerId = new HashSet(0);
     private Set organizationsForUpdatedBy = new HashSet(0);
     private Set dictionariesForCreatedBy = new HashSet(0);
     private Set projectsForUpdatedBy = new HashSet(0);
     private Set observationTuplesForUpdatedBy = new HashSet(0);
     private Set approvalRequestsForRequestorId = new HashSet(0);
     private Set dictionaryTermsForCreatedBy = new HashSet(0);
     private Set observationTuplesForCreatedBy = new HashSet(0);
     private Set programsForCreatedBy = new HashSet(0);
     private Set observationParametersForUpdatedBy = new HashSet(0);
     private Set projectsForCreatedBy = new HashSet(0);
     private Set organizationsForCreatedBy = new HashSet(0);
     private Set observationParametersForCreatedBy = new HashSet(0);
     private Set geographicZonesForCreatedBy = new HashSet(0);

    public User() {
    }

	
    public User(Organization organization, UserRole userRole, Person person, String username, String password, Date dateCreated, long createdBy) {

        this.organization = organization;
        this.userRole = userRole;
        this.person = person;
        this.username = username;
        this.password = password;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
    }
    public User(long userId, Organization organization, UserRole userRole, Person person, String username, String password, Date dateCreated, Date dateUpdated, Long updatedBy, long createdBy, Set approvalRequestsForUpdatedBy, Set stationsForUpdatedBy, Set dictionariesForUpdatedBy, Set dictionaryTermsForUpdatedBy, Set stationsForCreatedBy, Set geographicZonesForUpdatedBy, Set approvalRequestsForApproverId, Set approvalRequestsForCreatedBy, Set programsForUpdatedBy, Set programAdmins, Set programsForOwnerId, Set organizationsForUpdatedBy, Set dictionariesForCreatedBy, Set projectsForUpdatedBy, Set observationTuplesForUpdatedBy, Set approvalRequestsForRequestorId, Set dictionaryTermsForCreatedBy, Set observationTuplesForCreatedBy, Set programsForCreatedBy, Set observationParametersForUpdatedBy, Set projectsForCreatedBy, Set organizationsForCreatedBy, Set observationParametersForCreatedBy, Set geographicZonesForCreatedBy) {
       this.userId = userId;
       this.organization = organization;
       this.userRole = userRole;
       this.person = person;
       this.username = username;
       this.password = password;
       this.dateCreated = dateCreated;
       this.dateUpdated = dateUpdated;
       this.updatedBy = updatedBy;
       this.createdBy = createdBy;
       this.approvalRequestsForUpdatedBy = approvalRequestsForUpdatedBy;
       this.stationsForUpdatedBy = stationsForUpdatedBy;
       this.dictionariesForUpdatedBy = dictionariesForUpdatedBy;
       this.dictionaryTermsForUpdatedBy = dictionaryTermsForUpdatedBy;
       this.stationsForCreatedBy = stationsForCreatedBy;
       this.geographicZonesForUpdatedBy = geographicZonesForUpdatedBy;
       this.approvalRequestsForApproverId = approvalRequestsForApproverId;
       this.approvalRequestsForCreatedBy = approvalRequestsForCreatedBy;
       this.programsForUpdatedBy = programsForUpdatedBy;
       this.programAdmins = programAdmins;
       this.programsForOwnerId = programsForOwnerId;
       this.organizationsForUpdatedBy = organizationsForUpdatedBy;
       this.dictionariesForCreatedBy = dictionariesForCreatedBy;
       this.projectsForUpdatedBy = projectsForUpdatedBy;
       this.observationTuplesForUpdatedBy = observationTuplesForUpdatedBy;
       this.approvalRequestsForRequestorId = approvalRequestsForRequestorId;
       this.dictionaryTermsForCreatedBy = dictionaryTermsForCreatedBy;
       this.observationTuplesForCreatedBy = observationTuplesForCreatedBy;
       this.programsForCreatedBy = programsForCreatedBy;
       this.observationParametersForUpdatedBy = observationParametersForUpdatedBy;
       this.projectsForCreatedBy = projectsForCreatedBy;
       this.organizationsForCreatedBy = organizationsForCreatedBy;
       this.observationParametersForCreatedBy = observationParametersForCreatedBy;
       this.geographicZonesForCreatedBy = geographicZonesForCreatedBy;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public Long getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }
    public long getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(long createdBy) {
        this.createdBy = createdBy;
    }
    public Set getApprovalRequestsForUpdatedBy() {
        return this.approvalRequestsForUpdatedBy;
    }
    
    public void setApprovalRequestsForUpdatedBy(Set approvalRequestsForUpdatedBy) {
        this.approvalRequestsForUpdatedBy = approvalRequestsForUpdatedBy;
    }
    public Set getStationsForUpdatedBy() {
        return this.stationsForUpdatedBy;
    }
    
    public void setStationsForUpdatedBy(Set stationsForUpdatedBy) {
        this.stationsForUpdatedBy = stationsForUpdatedBy;
    }
    public Set getDictionariesForUpdatedBy() {
        return this.dictionariesForUpdatedBy;
    }
    
    public void setDictionariesForUpdatedBy(Set dictionariesForUpdatedBy) {
        this.dictionariesForUpdatedBy = dictionariesForUpdatedBy;
    }
    public Set getDictionaryTermsForUpdatedBy() {
        return this.dictionaryTermsForUpdatedBy;
    }
    
    public void setDictionaryTermsForUpdatedBy(Set dictionaryTermsForUpdatedBy) {
        this.dictionaryTermsForUpdatedBy = dictionaryTermsForUpdatedBy;
    }
    public Set getStationsForCreatedBy() {
        return this.stationsForCreatedBy;
    }
    
    public void setStationsForCreatedBy(Set stationsForCreatedBy) {
        this.stationsForCreatedBy = stationsForCreatedBy;
    }
    public Set getGeographicZonesForUpdatedBy() {
        return this.geographicZonesForUpdatedBy;
    }
    
    public void setGeographicZonesForUpdatedBy(Set geographicZonesForUpdatedBy) {
        this.geographicZonesForUpdatedBy = geographicZonesForUpdatedBy;
    }
    public Set getApprovalRequestsForApproverId() {
        return this.approvalRequestsForApproverId;
    }
    
    public void setApprovalRequestsForApproverId(Set approvalRequestsForApproverId) {
        this.approvalRequestsForApproverId = approvalRequestsForApproverId;
    }
    public Set getApprovalRequestsForCreatedBy() {
        return this.approvalRequestsForCreatedBy;
    }
    
    public void setApprovalRequestsForCreatedBy(Set approvalRequestsForCreatedBy) {
        this.approvalRequestsForCreatedBy = approvalRequestsForCreatedBy;
    }
    public Set getProgramsForUpdatedBy() {
        return this.programsForUpdatedBy;
    }
    
    public void setProgramsForUpdatedBy(Set programsForUpdatedBy) {
        this.programsForUpdatedBy = programsForUpdatedBy;
    }
    public Set getProgramAdmins() {
        return this.programAdmins;
    }
    
    public void setProgramAdmins(Set programAdmins) {
        this.programAdmins = programAdmins;
    }
    public Set getProgramsForOwnerId() {
        return this.programsForOwnerId;
    }
    
    public void setProgramsForOwnerId(Set programsForOwnerId) {
        this.programsForOwnerId = programsForOwnerId;
    }
    public Set getOrganizationsForUpdatedBy() {
        return this.organizationsForUpdatedBy;
    }
    
    public void setOrganizationsForUpdatedBy(Set organizationsForUpdatedBy) {
        this.organizationsForUpdatedBy = organizationsForUpdatedBy;
    }
    public Set getDictionariesForCreatedBy() {
        return this.dictionariesForCreatedBy;
    }
    
    public void setDictionariesForCreatedBy(Set dictionariesForCreatedBy) {
        this.dictionariesForCreatedBy = dictionariesForCreatedBy;
    }
    public Set getProjectsForUpdatedBy() {
        return this.projectsForUpdatedBy;
    }
    
    public void setProjectsForUpdatedBy(Set projectsForUpdatedBy) {
        this.projectsForUpdatedBy = projectsForUpdatedBy;
    }
    public Set getObservationTuplesForUpdatedBy() {
        return this.observationTuplesForUpdatedBy;
    }
    
    public void setObservationTuplesForUpdatedBy(Set observationTuplesForUpdatedBy) {
        this.observationTuplesForUpdatedBy = observationTuplesForUpdatedBy;
    }
    public Set getApprovalRequestsForRequestorId() {
        return this.approvalRequestsForRequestorId;
    }
    
    public void setApprovalRequestsForRequestorId(Set approvalRequestsForRequestorId) {
        this.approvalRequestsForRequestorId = approvalRequestsForRequestorId;
    }
    public Set getDictionaryTermsForCreatedBy() {
        return this.dictionaryTermsForCreatedBy;
    }
    
    public void setDictionaryTermsForCreatedBy(Set dictionaryTermsForCreatedBy) {
        this.dictionaryTermsForCreatedBy = dictionaryTermsForCreatedBy;
    }
    public Set getObservationTuplesForCreatedBy() {
        return this.observationTuplesForCreatedBy;
    }
    
    public void setObservationTuplesForCreatedBy(Set observationTuplesForCreatedBy) {
        this.observationTuplesForCreatedBy = observationTuplesForCreatedBy;
    }
    public Set getProgramsForCreatedBy() {
        return this.programsForCreatedBy;
    }
    
    public void setProgramsForCreatedBy(Set programsForCreatedBy) {
        this.programsForCreatedBy = programsForCreatedBy;
    }
    public Set getObservationParametersForUpdatedBy() {
        return this.observationParametersForUpdatedBy;
    }
    
    public void setObservationParametersForUpdatedBy(Set observationParametersForUpdatedBy) {
        this.observationParametersForUpdatedBy = observationParametersForUpdatedBy;
    }
    public Set getProjectsForCreatedBy() {
        return this.projectsForCreatedBy;
    }
    
    public void setProjectsForCreatedBy(Set projectsForCreatedBy) {
        this.projectsForCreatedBy = projectsForCreatedBy;
    }
    public Set getOrganizationsForCreatedBy() {
        return this.organizationsForCreatedBy;
    }
    
    public void setOrganizationsForCreatedBy(Set organizationsForCreatedBy) {
        this.organizationsForCreatedBy = organizationsForCreatedBy;
    }
    public Set getObservationParametersForCreatedBy() {
        return this.observationParametersForCreatedBy;
    }
    
    public void setObservationParametersForCreatedBy(Set observationParametersForCreatedBy) {
        this.observationParametersForCreatedBy = observationParametersForCreatedBy;
    }
    public Set getGeographicZonesForCreatedBy() {
        return this.geographicZonesForCreatedBy;
    }
    
    public void setGeographicZonesForCreatedBy(Set geographicZonesForCreatedBy) {
        this.geographicZonesForCreatedBy = geographicZonesForCreatedBy;
    }




}


